Repository SkywardAI/containers, pull requests merged in 2024-04, with the labels that each got.

#7 Installing from dynamic requirements.txt
  .dockerignore
  .github/workflows/ci.yml
  Dockerfile
  LICENSE
  requirements.txt
Labels: build, dependencies

#8 add ci to main
  .github/workflows/ci.yml
Labels: ci, build

#12 Bump kimchima to v0.3.0
  Makefile
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: build, dependencies

#16 update kimchima to 0.4.1
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: build

#18 Add backend dependencies
  .github/release-drafter.yml
  Dockerfile
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: dependencies, python

#19 split ci into build and release
  .github/workflows/build_check.yml
  .github/workflows/release_image.yml
Labels: enhancement, ci, build

#22 bump kimchima to v0.4.5
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement

#24 bump version to v0.1.9
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: dependencies, python

#25 feat add psycopg2-binary
  poetry.lock
  pyproject.toml
  requirements.txt
Labels: enhancement, dependencies
